-- SCRIPT PURPOSE : POPULATES A DEFAULT VALUE IN THE COLUMN IF DOESNOT EXIST IN THE TABLE

-- DECLARE VARIABLE FOR STRING COLUMN NAMES AND QUERY

DECLARE @ColVal AS NVARCHAR(100)
DECLARE @Query AS NVARCHAR(MAX)

-- LOGIC FOR POPULATING COLUMN WITH COLUMN VALUES FROM THE TABLE IF IT EXISTS OTHERWISE 
-- POPULATE COLUMN WITH DEFAULT VALUES OF N/A

SELECT @ColVal =     
CASE WHEN EXISTS
(
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA ='logs' and TABLE_NAME='metadata' 
    and COLUMN_NAME='current_user'
) 
THEN
(
    SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA ='logs' and TABLE_NAME='metadata' 
    and COLUMN_NAME='current_user'
)
ELSE
N'''N/A'''
END

-- STORING THE QUERY CONTAINING THE COLUMN VARIABLE VALUE

SET @Query =N'SELECT ' + @ColVal+ ' FROM logs.metadata GROUP BY subject_area';      

-- EXECUTING THE QUERY WITH THE LOGIC FOR POPULATING COLUMN

EXECUTE sp_executesql @Query

